Add action for Hyp3 Deployment for NISAR GUNW products
ASFHyP3/hyp3 pull request #1085
Opened 2022-06-28 00:58 UTC by cmarshak

Modified:

```
 - environment: hyp3-a19-jpl
            domain: hyp3-a19-jpl.asf.alaska.edu
            template_bucket: cf-templates-v4pvone059de-us-west-2
            image_tag: latest
            product_lifetime_in_days: 180
            quota: 0
            job_files: job_spec/INSAR_ISCE.yml job_spec/INSAR_ISCE_TEST.yml
            instance_types: c5d.xlarge
            default_max_vcpus: 1600
            expanded_max_vcpus: 1600
            required_surplus: 0
            security_environment: JPL-public
            ami_id: /aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id
            distribution_url: ''
```

Changing `hyp3-nisar-jpl` to `hyp3-nisar-jpl` and updating the template bucket use cloud formation to generate a bucket for storing cloud formation templates.

2022-06-28 01:04 UTC, jhkennedy requested changes
Do you also want to do `hyp3-tibet-jpl` in this same PR, or separate?

2022-06-28 01:04 UTC, jhkennedy commented on .github/workflows/deploy-enterprise.yml
> +            security_environment: JPL-public
```suggestion
            security_environment: JPL
```
I forgot to mention this bit -- we need to use the `JPL` security environment until the public bucket request is done. After we can switch it to `JPL-public` which will make the HyP3 content bucket public.

2022-06-28 01:06 UTC, cmarshak commented
> Do you also want to do `hyp3-tibet-jpl` in this same PR, or separate?

I am going to create a new pull request.

2022-06-28 01:30 UTC, jhkennedy commented
Looks good to me! Here's our (ASF) todos before merging/deploying:
- [ ] create an `hyp3-nisar-jpl` GitHub Actions environment like the `hyp3-a19-jpl` one
- [ ] populate the environment with necessary secrets
    - [ ] `AWS_REGION`
    - [ ] `V2_AWS_ACCESS_KEY_ID`
    - [ ] `V2_AWS_SECRET_ACCESS_KEY`
    - [ ] `EDL_USERNAME`
    - [ ] `EDL_PASSWORD`
    - [ ] `VPC_ID`
    - [ ] `SUBNET_ID`
    - [ ] CERTIFICATE_ARN`
- [ ] verify service user access keys (stored in account secrets manager) work

@cmarshak do you want to use the same Earthdata Login user as `hyp3-a19-jpl`, or create a new `hyp3-nisar` user?

2022-06-28 16:12 UTC, cmarshak commented
> @cmarshak do you want to use the same Earthdata Login user as `hyp3-a19-jpl`, or create a new `hyp3-nisar` user?

Let's use the same user for `a19` and elsewhere - will be too complicated to create multiple "operational users" that everyone has access to.

2022-06-29 05:34 UTC, jhkennedy commented
I've created the GitHub Actions environment and have populated all the secrets but `CERTIFICATE_ARN`. A new TLS certificate needs to be generated by ASF's Platform Team for `hyp3-nisar-jpl.asf.alaska.edu`, which I've requested. Then I will need to uploaded to the AWS account before I know it's ARN.

2022-06-30 05:47 UTC, jhkennedy approved these changes
TLS certificate was uploaded to the Certificate Manager and the the GitHub Actions environment should be fully populated! :shipit:

2022-06-30 05:48 UTC, merged