Ionosphere and Region of Interest updates to job spec for Test Branch
ASFHyP3/hyp3 pull request #1440
Opened 2023-01-24 18:37 UTC by cmarshak

@asjohnston-asf and @jhkennedy - this is a sample of what I am hoping for. I merged the new CLI into dev, but there is significantly more testing that has to be done.

I hope I can learn a few things as you update hyp3.

2023-01-24 18:43 UTC, cmarshak commented
The reference to the new parameters is here: https://github.com/ACCESS-Cloud-Based-InSAR/DockerizedTopsApp/blob/dev/isce2_topsapp/__main__.py#L94-L97

2023-02-01 01:59 UTC, jhkennedy requested changes
Let's separate out the framing from the ionosphere. 

we can address the ionosphere here (issue #1451) here while framing (issue #1452) will be addressed in #1464

2023-02-01 01:59 UTC, jhkennedy commented on job_spec/INSAR_ISCE_TEST.yml
> +        description: the frame-id derived from ARIA-S1-GUNW fixed frame convention; if specified, region of interest, must be too.
```suggestion
```

2023-02-01 01:59 UTC, jhkennedy commented on job_spec/INSAR_ISCE_TEST.yml
> +        - Ref::frame_id
```suggestion
        - --estimate-ionosphere-delay
        - Ref::estimate_ionosphere_delay
```

2023-02-06 20:20 UTC, jtherrmann approved these changes

2023-02-06 20:22 UTC, merged