Add flood maps
ASFHyP3/hyp3 pull request #954
Opened 2022-04-07 00:48 UTC by jacquelynsmale

2022-04-12 17:03 UTC, jtherrmann commented on job_spec/FLOOD_MAP.yml
> +WATER_MAP:
```suggestion
FLOOD_MAP:
```

2022-04-12 17:03 UTC, jtherrmann commented on job_spec/FLOOD_MAP_10M.yml
> +WATER_MAP:
```suggestion
FLOOD_MAP:
```

2022-04-12 17:08 UTC, jtherrmann requested changes
~~I'm not seeing a difference between `FLOOD_MAP.yml` and `FLOOD_MAP_10M.yml`, but I assume there should be? You might try running a diff of `WATER_MAP.yml` and `WATER_MAP_10M.yml` to see what might need to change (it's only a few lines), though I'm not sure if the changes would be exactly the same for the flood map spec.~~

2022-04-12 17:30 UTC, jtherrmann reviewed
Looks good apart from the requested changes. I don't have the background knowledge to verify that all of the parameters, default values, etc. are correct, so I'll let you judge if you're confident in those or if you want someone else with more expertise to add their review.

2022-04-12 17:34 UTC, jtherrmann commented on CHANGELOG.md
> +## [2.14.5]
This feels like a minor change, rather than a patch, to me.

2022-04-12 17:39 UTC, jtherrmann commented on CHANGELOG.md
> +- Flood depth map option added to test.
Just for added clarity, I'd suggest something along the lines of:

```suggestion
- Added `FLOOD_MAP` job spec (currently limited to `hyp3-test`).
```

2022-04-12 19:48 UTC, jtherrmann commented on .github/workflows/deploy-daac.yml
> +              job_spec/FLOOD_MAP.yml
No longer needed:
```suggestion
```

2022-04-12 20:05 UTC, jtherrmann requested changes

2022-04-12 20:05 UTC, jtherrmann commented
Self-reminder to diff the two job spec files before final approval.

2022-04-12 20:09 UTC, jtherrmann commented on job_spec/WATER_MAP.yml
> +    estimator:
Just as an example:
```suggestion
    flood_depth_estimator:
```

2022-04-12 20:10 UTC, jtherrmann commented on job_spec/WATER_MAP.yml
> +    - Ref::estimator
Continued from above:
```suggestion
    - Ref::flood_depth_estimator
```

2022-04-12 20:19 UTC, jtherrmann commented on job_spec/WATER_MAP.yml
> +    estimator:
@asjohnston-asf Do you know of a better way to make it clear that these parameters should only be used if `include_flood_depth` is `true`?

2022-04-12 20:50 UTC, asjohnston-asf commented on job_spec/WATER_MAP.yml
> +    estimator:
I can't think of anything better. Your suggestion for the parameter name(s) is a good one. Could also call out "ignored when include_flood_depth is false" in the description for each.

Could potentially combine `include_flood_depth` with another parameter, say add `none` as a `flood_depth_estimator` option, but that still leaves the problem of linking with the other parameters.

Could address the relationship at the API level by having the flood depth parameters be their own dictionary, e.g. 
```
"job_parameters": {
  "resolution": 30.0,
  "flood_depth": {
    "estimator": "nmad",
    "water_level_sigma": 3.0
  }
}
```
but I suspect that would take significant refactoring to get those values handed off as individual command line parameter key/value pairs to the Batch container

2022-04-13 17:17 UTC, jtherrmann approved these changes

2022-04-13 17:25 UTC, merged